import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import './globals.css'

import { QueryClientProvider } from '@/providers/query-client.provider'
import { ToasterProvider } from '@/providers/toaster.provider'

const inter = Montserrat({
	subsets: ['latin'],
	weight: ['500', '700', '900'],
})

export const metadata: Metadata = {
	title: 'Milestone.',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<QueryClientProvider>
				<body
					className={`${inter.className} antialiased bg-white h-[100dvh]`}
				>
					{children}
					<ToasterProvider />
				</body>
			</QueryClientProvider>
		</html>
	)
}
